In [4]:
!unzip -qo /content/archive.zip -d /data

import pandas as pd
from split_zip_file import Split_zip_file      #class1
from kaggriculture_df import Kaggriculture_df  #class2
from dir_to_strong import DirToStrong          #class3
from dirtobeginner import DirToBeginner

In [5]:
Split_zip_file("/data", 30)

1件のjsonではないファイルを検出しました👨‍🔧🗾
内容は以下になります。👇
['manifest.csv']を削除しました
データを 30 分割しました（1グループあたり約 23 件ずつ処理します）
========================

【成功】第1グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_0' へ仕分けました！
【成功】第2グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_1' へ仕分けました！
【成功】第3グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_2' へ仕分けました！
【成功】第4グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_3' へ仕分けました！
【成功】第5グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_4' へ仕分けました！
【成功】第6グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_5' へ仕分けました！
【成功】第7グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_6' へ仕分けました！
【成功】第8グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_7' へ仕分けました！
【成功】第9グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_8' へ仕分けました！
【成功】第10グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_9' へ仕分けました！
【成功】第11グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_10' へ仕分けました！
【成功】第12グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_11' へ仕分けました！
【成功】第13グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_12' へ仕分けました！
【成功】第14グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_13' へ仕分けました！
【成功】第15グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_14' へ仕分けました！
【成功】第16グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_15' へ仕分けました！
【成功】第17グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_16' へ仕分けました！
【成功】第18グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_17' へ仕分けました！
【成功】第19グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_18' へ仕分けました！
【成功】第20グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_19' へ仕分けました！
【成功】第21グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_20' へ仕分けました！
【成功】第22グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_21' へ仕分けました！
【成功】第23グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_22' へ仕分けました！
【成功】第24グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_23' へ仕分けました！
【成功】第25グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_24' へ仕分けました！
【成功】第26グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_25' へ仕分けました！
【成功】第27グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_26' へ仕分けました！
【成功】第28グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_27' へ仕分けました！
【成功】第29グループの 23 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_28' へ仕分けました！
【成功】第30グループの 8 件を、変数 'all_data_1' に一時格納し、フォルダ 'group_29' へ仕分けました！

✨ すべてのファイルの30分割リネームとフォルダ仕分けが完了しました！

In [6]:

DirToStrong(
    target_dir="/data",
    output_dir="/st_data",
    top_percent=0.01
)

DirToBeginner(
    target_dir="/data",
    output_dir = "/be_data",
    top_percent = 0.5
)

--- 処理を開始します ---
フロー1 & 3: 全フォルダのJSONファイルを走査し、スコアを抽出中...
抽出ボーダーライン計算完了: 上位 1.0% の基準額は 143491.61 です。
フロー2 & 4: 上位プレイヤーのデータを抽出・出力中...
[1位] プレイヤー1 (スコア:157577.0) のJSONをコピーしました: strong_rank1_score157577.0_p1.json
[2位] プレイヤー0 (スコア:157005.0) のJSONをコピーしました: strong_rank2_score157005.0_p0.json
[3位] プレイヤー1 (スコア:150533.0) のJSONをコピーしました: strong_rank3_score150533.0_p1.json
[4位] プレイヤー0 (スコア:149240.0) のJSONをコピーしました: strong_rank4_score149240.0_p0.json
[5位] プレイヤー1 (スコア:148193.0) のJSONをコピーしました: strong_rank5_score148193.0_p1.json
[6位] プレイヤー1 (スコア:146250.0) のJSONをコピーしました: strong_rank6_score146250.0_p1.json
[7位] プレイヤー0 (スコア:145329.0) のJSONをコピーしました: strong_rank7_score145329.0_p0.json
[8位] プレイヤー1 (スコア:145177.0) のJSONをコピーしました: strong_rank8_score145177.0_p1.json
[9位] プレイヤー0 (スコア:145111.0) のJSONをコピーしました: strong_rank9_score145111.0_p0.json
[10位] プレイヤー1 (スコア:144477.0) のJSONをコピーしました: strong_rank10_score144477.0_p1.json
[11位] プレイヤー0 (スコア:144322.0) のJSONをコピーしました: strong_rank11_score144322.0_p0.json
[12位] プレイヤー1 (スコア:144221.0) のJSONをコピーしました: strong_rank12_score144221.0_p1.json
[13位] プレイヤー0 (スコア:143927.0) のJSONをコピーしました: strong_rank13_score143927.0_p0.json
[14位] プレイヤー1 (スコア:143742.0) のJSONをコピーしました: strong_rank14_score143742.0_p1.json
--- 処理が完了しました ---
--- 処理を開始します ---
フロー1 & 3: 全フォルダのJSONファイルを走査し、スコアを抽出中...
抽出ボーダーライン計算完了: 50.0% の基準額は 83150.0 です。
フロー2 & 4: 対象プレイヤーのデータを抽出・出力中...
[1件目] プレイヤー1 (スコア:83174.0) のJSONをコピーしました: beginner_rank1_score83174.0_p1.json
[2件目] プレイヤー0 (スコア:83184.0) のJSONをコピーしました: beginner_rank2_score83184.0_p0.json
[3件目] プレイヤー1 (スコア:83272.0) のJSONをコピーしました: beginner_rank3_score83272.0_p1.json
[4件目] プレイヤー0 (スコア:83375.0) のJSONをコピーしました: beginner_rank4_score83375.0_p0.json
[5件目] プレイヤー0 (スコア:83386.0) のJSONをコピーしました: beginner_rank5_score83386.0_p0.json
[6件目] プレイヤー0 (スコア:83440.0) のJSONをコピーしました: beginner_rank6_score83440.0_p0.json
[7件目] プレイヤー0 (スコア:83526.0) のJSONをコピーしました: beginner_rank7_score83526.0_p0.json
[8件目] プレイヤー0 (スコア:83560.0) のJSONをコピーしました: beginner_rank8_score83560.0_p0.json
[9件目] プレイヤー1 (スコア:83612.0) のJSONをコピーしました: beginner_rank9_score83612.0_p1.json
[10件目] プレイヤー0 (スコア:83701.0) のJSONをコピーしました: beginner_rank10_score83701.0_p0.json
[11件目] プレイヤー1 (スコア:83740.0) のJSONをコピーしました: beginner_rank11_score83740.0_p1.json
[12件目] プレイヤー0 (スコア:83773.0) のJSONをコピーしました: beginner_rank12_score83773.0_p0.json
[13件目] プレイヤー1 (スコア:83798.0) のJSONをコピーしました: beginner_rank13_score83798.0_p1.json
[14件目] プレイヤー1 (スコア:83932.0) のJSONをコピーしました: beginner_rank14_score83932.0_p1.json
[15件目] プレイヤー0 (スコア:83995.0) のJSONをコピーしました: beginner_rank15_score83995.0_p0.json
--- 処理が完了しました ---

In [7]:
df1 = (Kaggriculture_df("/st_data/strong_rank1_score157577.0_p1.json", 1)).df
df2 = (Kaggriculture_df("/be_data/beginner_rank10_score83701.0_p0.json", 0)).df

In [8]:
df1

,step,day,money,tiles,farmer_x_y,hands_n,hires_today,unlocked_quadrants,private_shed,private_seeds,...,hands_action_list_11,hands_action_list_12,hands_action_list_13,hands_action_list_14,hands_action_list_15,hands_action_list_16,hands_action_list_17,hands_action_list_18,hands_action_list_19,hands_action_list_20
0,0,0,3000.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",0,0,[NW],"{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
1,1,0,22.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 2, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
2,2,0,50.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 2, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
3,3,0,22.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
4,4,0,50.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[3, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,715,29,144726.0,"[[None, None, None, None, None, None, {'consec...","[5, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
716,716,29,146959.0,"[[None, None, None, None, None, None, {'consec...","[5, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
717,717,29,156142.0,"[[None, None, None, None, None, None, {'consec...","[4, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
718,718,29,157185.0,"[[None, None, None, None, None, None, {'consec...","[4, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
719,719,29,157577.0,"[[None, None, None, None, None, None, {'consec...","[4, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[DROP],[None],[None],[None],[None],[None],[None],[None],[None],[None]

In [9]:
df2

,step,day,money,tiles,farmer_x_y,hands_n,hires_today,unlocked_quadrants,private_shed,private_seeds,...,hands_action_list_11,hands_action_list_12,hands_action_list_13,hands_action_list_14,hands_action_list_15,hands_action_list_16,hands_action_list_17,hands_action_list_18,hands_action_list_19,hands_action_list_20
0,0,0,3000.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",0,0,[NW],"{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
1,1,0,22.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 2, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
2,2,0,50.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 2, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
3,3,0,22.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[4, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
4,4,0,50.0,"[[None, None, None, None, None, LOCKED, LOCKED...","[3, 4]",5,5,[NW],"{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 12, 'STRAWBERRY': 0, 'T...",...,[None],[None],[None],[None],[None],[None],[None],[None],[None],[None]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,715,29,77680.0,"[[None, None, None, None, None, None, {'consec...","[5, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
716,716,29,79498.0,"[[None, None, None, None, None, None, {'consec...","[5, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
717,717,29,82813.0,"[[None, None, None, None, None, None, {'consec...","[4, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
718,718,29,83312.0,"[[None, None, None, None, None, None, {'consec...","[4, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[SOUTH],[None],[None],[None],[None],[None],[None],[None],[None],[None]
719,719,29,83701.0,"[[None, None, None, None, None, None, {'consec...","[4, 4]",11,11,"[NW, NE, SW]","{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER'...","{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TO...",...,[DROP],[None],[None],[None],[None],[None],[None],[None],[None],[None]

In [11]:
!zip -r output.zip "/be_data"
!zip -r output.zip "/st_data"

updating: be_data/ (stored 0%)
updating: be_data/beginner_rank11_score83740.0_p1.json (deflated 98%)
updating: be_data/beginner_rank10_score83701.0_p0.json (deflated 99%)
updating: be_data/beginner_rank2_score83184.0_p0.json (deflated 99%)
updating: be_data/beginner_rank13_score83798.0_p1.json (deflated 98%)
updating: be_data/beginner_rank7_score83526.0_p0.json (deflated 99%)
updating: be_data/beginner_rank4_score83375.0_p0.json (deflated 99%)
updating: be_data/beginner_rank8_score83560.0_p0.json (deflated 99%)
updating: be_data/beginner_rank5_score83386.0_p0.json (deflated 99%)
updating: be_data/beginner_rank6_score83440.0_p0.json (deflated 99%)
updating: be_data/beginner_rank9_score83612.0_p1.json (deflated 99%)
updating: be_data/beginner_rank12_score83773.0_p0.json (deflated 99%)
updating: be_data/beginner_rank14_score83932.0_p1.json (deflated 99%)
updating: be_data/beginner_rank15_score83995.0_p0.json (deflated 99%)
updating: be_data/beginner_rank3_score83272.0_p1.json (deflated 99%)
updating: be_data/beginner_rank1_score83174.0_p1.json (deflated 99%)
  adding: st_data/ (stored 0%)
  adding: st_data/strong_rank2_score157005.0_p0.json (deflated 99%)
  adding: st_data/strong_rank8_score145177.0_p1.json (deflated 99%)
  adding: st_data/strong_rank4_score149240.0_p0.json (deflated 99%)
  adding: st_data/strong_rank7_score145329.0_p0.json (deflated 99%)
  adding: st_data/strong_rank6_score146250.0_p1.json (deflated 99%)
  adding: st_data/strong_rank3_score150533.0_p1.json (deflated 98%)
  adding: st_data/strong_rank12_score144221.0_p1.json (deflated 99%)
  adding: st_data/strong_rank11_score144322.0_p0.json (deflated 99%)
  adding: st_data/strong_rank13_score143927.0_p0.json (deflated 99%)
  adding: st_data/strong_rank5_score148193.0_p1.json (deflated 99%)
  adding: st_data/strong_rank10_score144477.0_p1.json (deflated 99%)
  adding: st_data/strong_rank1_score157577.0_p1.json (deflated 99%)
  adding: st_data/strong_rank9_score145111.0_p0.json (deflated 99%)
  adding: st_data/strong_rank14_score143742.0_p1.json (deflated 99%)